{{- if .Values.aadpodidentitybinding.create }}
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ default (printf "%s-aadpodidentitybinding" .Release.Name) .Values.aadpodidentitybinding.name }}
  labels:
    {{- include "aspnetcore.standardLabels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  azureIdentity: {{ .Values.aadpodidentitybinding.identityName }}
  selector: {{ .Values.aadpodidentitybinding.identityName }}
{{- end }}
