{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aspnetcore.serviceAccountName" . }}
  labels:
    {{- include "aspnetcore.standardLabels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.azureWorkloadIdentity.enabled }}
    azure.workload.identity/use: "true"
    {{- end }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
