name: Renovate

on:
  workflow_dispatch: {}
  schedule:
    - cron: "7 2 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Use Node.js 18
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 18

      - name: Renovate
        shell: bash
        run: npx renovate $GITHUB_REPOSITORY
        env:
          RENOVATE_CONFIG_FILE: "renovate.json"
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          LOG_LEVEL: "debug"