name: Renovate

on:
  workflow_dispatch: {}
  schedule:
    - cron: "7 2 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Use Node.js 18
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: 18

      - name: Renovate
        shell: bash
        run: npx renovate $GITHUB_REPOSITORY
        env:
          RENOVATE_CONFIG_FILE: "renovate.json"
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          LOG_LEVEL: "debug"